using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using TouristGuide.Api.Data;

#nullable disable

namespace TouristGuide.Api.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515120000_EnsureTouristLocationSampleTable")]
    public partial class EnsureTouristLocationSampleTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS tourist_location_sample (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    tourist_id bigint NULL,
                    session_id character varying(64) NOT NULL,
                    region_id bigint NULL,
                    lat numeric NOT NULL,
                    lng numeric NOT NULL,
                    recorded_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_tourist_location_sample" PRIMARY KEY (id),
                    CONSTRAINT "FK_tourist_location_sample_region_region_id"
                        FOREIGN KEY (region_id) REFERENCES region (id) ON DELETE SET NULL,
                    CONSTRAINT "FK_tourist_location_sample_tourist_tourist_id"
                        FOREIGN KEY (tourist_id) REFERENCES tourist (id) ON DELETE SET NULL
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_tourist_location_sample_recorded_at_region_id"
                    ON tourist_location_sample (recorded_at, region_id);
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_tourist_location_sample_region_id"
                    ON tourist_location_sample (region_id);
                """);

            migrationBuilder.Sql("""
                CREATE INDEX IF NOT EXISTS "IX_tourist_location_sample_tourist_id"
                    ON tourist_location_sample (tourist_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
